APP_NAME = "JARVIS"

WAKE_WORD = "jarvis"

VOICE_TIMEOUT = 5

VOICE_PHRASE_LIMIT = 10

CHAT_TYPING_DELAY = 1000
VOICE_TIMEOUT = 5
VOICE_PHRASE_LIMIT = 10

CHAT_TYPING_DELAY = 1000

# Assistant remains awake for 20 seconds
AWAKE_TIMEOUT = 20